version: '3.8'
services:
  frontend:
    volumes:
      - ./frontend/src:/app/src:ro
      - ./frontend/public:/app/public:ro
      - ./frontend/index.html:/app/index.html:ro
      - frontend_node_modules:/app/node_modules
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: frontend/Dockerfile.dev
    container_name: trading-ai-frontend-dev
    environment:
      - NODE_ENV=development
      - DOCKER=true
    command: npm run dev -- --host 0.0.0.0 --port 8080
    depends_on:
      - backend

volumes:
  frontend_node_modules:
